module.exports.ai = require(`./ai.js`)
module.exports.gql = require(`./gql.js`)
module.exports.helix = require(`./helix.js`)
module.exports.ivr = require(`./ivr.js`)
module.exports.stv = require(`./stv.js`)
module.exports.supinic = require(`./supinic.js`)
