module.exports = require(`./utils.js`)
module.exports.coins = require(`./coins.js`)
module.exports.cooldown = require(`./cooldown.js`)
module.exports.croc = require(`./crocodile.js`)
module.exports.logger = require(`./logger.js`)
module.exports.regex = require(`./regex.js`)
